apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  name: backend-sealed-secret
  namespace: tumeplay
spec:
  encryptedData:
    MONDIALRELAY_ID: >-
      AgCTmV0sxKR7ZjwL8RSQrh6F+mtqqkwZsOzAZK3w3K4owLKlrrq5dwJrUcRY/pvFwVFtas6WyEGasVA7IGjnkO31S3yvE01W3bERwxWEAi1V/gkmlL+eCOCsJ5+b/DVJo49suemEZJ0CykZuuxWVbJM0cqXFiOioDnH35HsZPEf62D5nsVvrPMD57rjLU1a961/8/PEFm7y9niD/gfa8eBpTDUFdLwvJWiBKsVye8CYEFhsrfBl4lvbgv8aDHoJqk9kOh3XM1FIuCYrozWdagAaf1eg+gBC2NmFhyTXzXdKDJmVslJPQIctPojDFBA7jeZLR/6HBXnBml4U3chNUPqUgazoA2ur9RBfqaNZ9e1HEJbLtnV91WYMcBttxNMBSIGjcs6QxzC6MQrUehPjudTzswLNJeG0PW4tfbybxZOn3INVSFq62CMQbNajupkus1hKejKB/JUsBNBsL7LDmNpXfMVJ8XC0grKanzhErgN9deMg7CdFbHMoCjMqA0xaO1y/WEnuFYeYY/7/SseBhbWFuN9JqhdM8KFXDOflkZqlsJbf4+iLtn71/6YDouHpAlwwLZTwPuyM8jrvxXZCnbrzBgQsL1WpuoyQWIC4t/YJ0lS7A6B8WveN42psFLjOx1CX30zMk77oldx3njW4pukkMNG6h7ItM4SNA//uvfrpQ/Ef1nWjKzHRkvNSiCfE9UQrJ3R4ufdnGBw==
    MONDIALRELAY_SECRET: >-
      AgAKewcqqaSqyzuyCl9T+f7OnADH5DJnanNeeR3rlhUz+ukIKSbWIYhRrMCp4zclDwMl88T8zSnp1ju8nSv20jEgvUk8g9zJ354oVHZ4PBGeodtAtJKqltrjc3PFDXWRs3cCU4Rut3jCTP9z0tA5k5WUNRqi2vsTR+oDXnW3hCTDGs6fOXy8jLFM95mur3bj09IZL04lLNvyXlaEbzHLUr+wM4rLr4co06EEdI0kaXZLx2Ns8lkEroWwh7gh5XoL24LCKVsdYvUB7MS4Q0m+tQ5TX6Grhx7o9GqW2Qc+mMKkht78B4CKRcSB8pFPzW6RmHAChNTvFnAuOc1U/5K6zZk/mlJTwebxT1bZsEuoJ1tqVy9MZh71jyg97QTmpepDuSY0JM2sHip20/Lsvf4TyKdmLuY9G+oSbjJYtARWzzBtXvj6NQ4DMpSPAPAPnNBxGy3tXkqyLxsEnJ32gAcD2Qzg/asSqvZzLi0MyzP9RP+ve9/14qN19m4ChwbtkTIK5viEi/o585tUM+3sPChBhrkPk/07Efpm+qhkfzBY5fWF8smpyWelZa1+rtYS/vZb9d9YRPgBuEEvGaIgcAWJGGA9IzRMB+JphfhDxS4zDnUWDoRRY+bAyqAfk+zZq+3VvJ+5njyjY1PpcBerT4tFICRtlNOof6XNwTrqHDQ806Fat+296dMkfqEyVF1U5/zrE+1z3X2d10ZvZA==
    EMAIL_PROVIDER_PASSWORD: >-
      AgDEAbsDpdFX/nKL15CCy47ledwCSYjkZc+o/kcALZudXKA6ukPOnAjUS4PwS7QjSmf8xOt2SAMJSyUkHsGZ3UYo4NAXRgpvO+CfBqV5kImCIQN93op90W1wdKh8OnXb6QslHpAGFmlZ20RMp3XXecQJps6MnV+Hh7WzaYlWEukVmyniPaPLF0P8TvHii77k+dTW5BqSuRlgQRC8NBcXnrqVRHLjKGWYBlm/6bHipQwIaxvNbYfmVbiHULLfC1gokrcXDfQQRFRerzRT4V1enZcRVDs/e22XXjAsRTxW+NKulOds+RfxVud82CbzL7qW7/JQf72BhPR/NeTdJ11s8ULpTx3iQylg/3yWwIirPxiWykm7YFY121MZY+b6JNRGlbfTRriDu9e2n+EKVdlH4IveI0E1UNXdEb3HtmYpbgWUpMIQqBMr//sbPVkBNqqF9zcC/BPUGei81FxSnFWcmHorNXLrXrEbl+XG+6zUlf0DgCNMeHEuHZEUKU7G7vHgTJhenKMfM0Lu5YhjIHC9E7J2/N+ubVzw+NA2ITKGoJ9rNrxY2gDayA/tsV49Cv2y1NbN+/6GpeYORBjO9r82cU6T29tAySCyHAF2l1Va5Swu9cGJ+wyqIKG1Wpw/HZaWYbys74m6Eg1u3hWNGK566pJVb3HTzwgCc3FMd+sDR5BjV37XkHsrsYoL/cWMOVyiJ5fchZQJmACOLY9q5A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
      name: backend-sealed-secret
    type: Opaque
