pg:
  ~chart: pg

dashboard:
  host: "bo-tumeplay-preprod.dev.fabrique.social.gouv.fr"

backend:
  ~needs: [build-backend, pg]
  envFrom:
    - secretRef:
        name: "pg-app"
    - secretRef:
        name: backend-sealed-secret
    - configMapRef:
        name: backend-configmap

jobs:
  runs:
    build-frontend-guyane:
      with:
        buildArgs:
          buildenv: preprod.guyane

    build-frontend-aime:
      with:
        buildArgs:
          buildenv: preprod.aime
