projectName: tumeplay
ciNamespace: ci-tumeplay

dependencies:
  fabrique:
    extends:
      - name: ovh
      - name: buildkit-service
    dependencies:
      contrib:
        preDeploy:
          importSecrets:
            options:
              secrets:
                kubeconfig:
                harbor:
                buildkit-client-certs:
                tumeplay-dev-backups-access-key:
                tumeplay-prod-backups-access-key:
